#!/bin/bash
set -eu

# Install the latest Docker
apt-get install --no-install-recommends --yes \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) stable"
apt-get update
apt-get install --no-install-recommends --yes \
    docker-ce docker-ce-cli containerd.io
apt-get install wget


cp /djangos.service /etc/systemd/system/djangos.service
cp /rc.local /etc/rc.local
chmod +x /etc/rc.local
apt-get install python3 -y
apt-get update -y
apt-get install python3 -y
apt-get install python3-pip -y
apt-get update -y
pip3 install django
pip3 install gunicorn



